[project]
name = "boobsting"
version = "0.1.0"
description = "Repo with training of boosting / bagging and so one algorithms"
readme = "README.md"
authors = [
    { name = "Beresnev Aleksei", email = "meikuam@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "catboost>=1.2.10",
    "dotenv>=0.9.9",
    "imbalanced-learn>=0.14.2",
    "jupyterlab>=4.6.3",
    "kagglehub>=1.0.2",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.1",
    "nltk>=3.10.3",
    "optuna>=4.9.0",
    "pandas>=3.0.5",
    "polars>=1.43.2",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "shap>=0.52.0",
    "tqdm>=4.70.0",
    "xgboost>=3.4.0",
]

[project.scripts]
boobsting = "boobsting:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
